fix for WrapMysqlModifySubqueryTransformation when using join builder
Fixes and error where .andOnIn() causes:
"TypeError: parentQuery.isUpdate is not a function"